# Copyright (C) 2015 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: swizec@reciprocitylabs.com
# Maintained By: swizec@reciprocitylabs.comlanguage: python

python:
  - "2.7"
sudo: false  # to enable container-based infrastructure
services: mysql
virtualenv:
  system_site_packages: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - "wget https://commondatastorage.googleapis.com/appengine-sdks/deprecated/193/google_appengine_1.9.3.zip  -nv"
  - "unzip -qd src google_appengine_1.9.3.zip"
  - "mv src/google_appengine/google src/"
  - "pip install --user -r src/requirements.txt"
  - "pip install --user -r src/dev-requirements.txt"
  - "pip install --user google-api-python-client"
  - "pip install --user mysql-python"
  - "pip install --user webob"
  - 'gem install sass --version "=3.4.9"'
  - 'gem install compass --version "=1.0.1"'
  - npm install karma karma-jasmine jasmine-core phantomjs karma-chrome-launcher bower
  - bower install
before_script:
  - "source bin/init_env"
  - make bower_components
  - build_compass
  - build_assets
script:
  - bin/run_travis_tests
  - ./node_modules/karma/bin/karma start karma.conf.js --single-run
notifications:
  email: false
