# Copyright (C) 2019 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

version: "2"
services:
  cleandev:
    extends:
      service: cleandev
      file: common-services.yml
    ports:
     - "127.0.0.1:8000:8000"
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:9876:9876"
    depends_on:
      - db
    networks:
      - network_cleandev
      - selenium
  cleandev_destructive:
    extends:
      service: cleandev
      file: common-services.yml
    depends_on:
      - db_destructive
    networks:
      - network_cleandev_destructive
      - selenium
  db:
    extends:
      service: db
      file: common-services.yml
    networks:
      - network_cleandev
  db_destructive:
    extends:
      service: db
      file: common-services.yml
    networks:
      network_cleandev_destructive:
        aliases:
          - db
  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    volumes:
     - "./test/selenium:/selenium"
     - "/dev/shm:/dev/shm"
    depends_on:
      - cleandev
      - cleandev_destructive
    networks:
      - selenium
    environment:
     - "TZ=America/Los_Angeles"
     - PYTHONDONTWRITEBYTECODE=true
     - PYTHONPATH=/selenium/src
     - SCREEN_WIDTH=1440
     - SCREEN_HEIGHT=900
networks:
  network_cleandev:
  network_cleandev_destructive:
  selenium:
