# Copyright (C) 2019 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

version: "2"
services:
  cleandev:
    extends:
      service: cleandev
      file: common-services.yml
    depends_on:
      - db
    networks:
      - network_cleandev
  db:
    extends:
      service: db
      file: common-services.yml
    networks:
      - network_cleandev
networks:
  network_cleandev:
