cleandev:
  build: .
  dockerfile: Dockerfile-clean
  ports:
   - "8000:8000"
   - "8080:8080"
   - "9876:9876"
  volumes:
   - ".:/vagrant"
  environment:
   - PYTHONDONTWRITEBYTECODE=true
   - NODE_PATH=/vagrant-dev/node_modules/
   - GGRC_DATABASE_URI=mysql+mysqldb://root:root@db/ggrcdev?charset=utf8
   - GGRC_DATABASE_HOST=db
  links:
   - db
db:
  image: mysql:5.5
  volumes:
  - "./provision/docker/mysql:/etc/mysql/conf.d"
  environment:
  - MYSQL_ROOT_PASSWORD=root
