version: "2"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHROME_DRIVER_VERSION: "2.33"
    volumes:
     - ".:/vagrant"
     - ".:/vagrant_bind"
    ports:
     - "127.0.0.1:8001:8000"
     - "127.0.0.1:8081:8080"
     - "127.0.0.1:9877:9876"
    environment:
     - PYTHONDONTWRITEBYTECODE=true
     - NODE_PATH=/vagrant-dev/node_modules/
     - GGRC_DATABASE_URI=mysql+mysqldb://root:root@db/ggrcdev?charset=utf8
     - GGRC_DATABASE_HOST=db
    links:
     - db

  db:
    image: mysql:5.6
    volumes:
     - "./provision/docker/mysql:/etc/mysql/conf.d"
    environment:
     - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql/:rw,noexec,nosuid,size=1G

  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    volumes:
     - "./test/selenium:/selenium"
     - "/dev/shm:/dev/shm"
    links:
     - dev
    environment:
     - "TZ=America/Los_Angeles"
     - PYTHONDONTWRITEBYTECODE=true
     - PYTHONPATH=/selenium/src
     - SCREEN_WIDTH=1440
     - SCREEN_HEIGHT=900
