# Copyright (C) 2019 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

version: "2"
services:
  cleandev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "127.0.0.1:8000:8000"
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:9876:9876"
     - "127.0.0.1:9222:9222"
    volumes:
     - ".:/vagrant"
    environment:
     - PYTHONDONTWRITEBYTECODE=true
     - NODE_PATH=/vagrant-dev/node_modules/
     - GGRC_DATABASE_URI=mysql+mysqldb://root:root@db/ggrcdev?charset=utf8
     - GGRC_DATABASE_HOST=db
    links:
     - db
  db:
    image: mysql:5.6.36
    ports:
     - "127.0.0.1:3306:3306"
    volumes:
     - "./provision/docker/mysql:/etc/mysql/conf.d"
    environment:
     - MYSQL_ROOT_PASSWORD=root
