# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

---
- name: install common packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
