# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
ggrc_development_directories:
  - name: /vagrant-dev
  - name: /vagrant-dev/opt
  - name: /vagrant-dev/tmp
  - name: /vagrant/tmp

ggrc_global_npm_modules:
  - name: nodeunit
  - name: pegjs
  - name: karma-cli
  - name: karma-junit-reporter
  - name: jasmine-core
  - name: mkdirp
  - name: bower
  - name: eslint
  - name: eslint-config-google

ggrc_local_npm_modules:
  - name: karma
  - name: karma-jasmine

ggrc_gems:
  - name: 'sass'
    version: '3.2.13'
  - name: 'compass'
    version: '0.12.2'

ggrc_databases:
  - name: ggrcdev
  - name: ggrctest
