# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

---
- name: restart mysql
  sudo: yes
  service:
    name: mysql
    enabled: yes
    state: restarted
